/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javanetworkex2;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.text.DecimalFormat;


/**
 *
 * @author k00223375
 */
public class JNEx2Client extends javax.swing.JFrame {

    /**
     * Creates new form JNEx2Client
     */
    static DecimalFormat twoDigits = new DecimalFormat("0.00");
    
    DataOutputStream osToServer;
    DataInputStream isFromServer;
    Socket connectToServer;

    public JNEx2Client() {
        initComponents();

        try {
            // Create a socket to connect to the server
            // Socket connectToServer = new Socket("130.254.32.8", 8000);
            connectToServer = new Socket("localhost", 8111);

            // Create an input stream to receive data from the server
            isFromServer = new DataInputStream(connectToServer.getInputStream());

            // Create an output stream to send data to the server
            osToServer = new DataOutputStream(connectToServer.getOutputStream());

        } catch (IOException ex) {
            System.err.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        CtFButton = new javax.swing.JButton();
        CtKButton = new javax.swing.JButton();
        FtCButton = new javax.swing.JButton();
        FtKButton = new javax.swing.JButton();
        KtCButton = new javax.swing.JButton();
        KtFButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        outputField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Your Temperature Value:");

        CtFButton.setText("Celsius to Fahrenheit");
        CtFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtFButtonActionPerformed(evt);
            }
        });

        CtKButton.setText("Celcius To Kelvin");
        CtKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtKButtonActionPerformed(evt);
            }
        });

        FtCButton.setText("Fahrenheit to Celcius");
        FtCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FtCButtonActionPerformed(evt);
            }
        });

        FtKButton.setText("Fahrenheit to Kelvin");
        FtKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FtKButtonActionPerformed(evt);
            }
        });

        KtCButton.setText("Kelvin to Celsius");
        KtCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KtCButtonActionPerformed(evt);
            }
        });

        KtFButton.setText("Kelvin to Fahrenheit");
        KtFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KtFButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Coverted Value:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputField)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CtFButton)
                            .addComponent(FtCButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KtCButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FtKButton)
                    .addComponent(CtKButton)
                    .addComponent(KtFButton)
                    .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CtFButton)
                    .addComponent(CtKButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FtCButton)
                    .addComponent(FtKButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KtCButton)
                    .addComponent(KtFButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CtKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtKButtonActionPerformed
        // TODO add your handling code here:
        Double input = Double.parseDouble(inputField.getText());
        String inputS="CtK";
        try {
            osToServer.writeDouble(input);
            osToServer.writeUTF(inputS);
            osToServer.flush();
            
            double answer = isFromServer.readDouble();
            outputField.setText(twoDigits.format(answer));
        } catch (IOException ex) {
            System.err.println(ex);
        }


    }//GEN-LAST:event_CtKButtonActionPerformed

    private void CtFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtFButtonActionPerformed
        // TODO add your handling code here:
        Double input = Double.parseDouble(inputField.getText());
        String inputS="CtF";
        try {
            osToServer.writeDouble(input);
            osToServer.writeUTF(inputS);
            osToServer.flush();
            
            double answer = isFromServer.readDouble();
            outputField.setText(twoDigits.format(answer));
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_CtFButtonActionPerformed

    private void FtCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FtCButtonActionPerformed
        // TODO add your handling code here:
        Double input = Double.parseDouble(inputField.getText());
        String inputS="FtC";
        try {
            osToServer.writeDouble(input);
            osToServer.writeUTF(inputS);
            osToServer.flush();
            
            double answer = isFromServer.readDouble();
            outputField.setText(twoDigits.format(answer));
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_FtCButtonActionPerformed

    private void KtCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KtCButtonActionPerformed
        // TODO add your handling code here:
        Double input = Double.parseDouble(inputField.getText());
        String inputS="KtC";
        try {
            osToServer.writeDouble(input);
            osToServer.writeUTF(inputS);
            osToServer.flush();
            
            double answer = isFromServer.readDouble();
            outputField.setText(twoDigits.format(answer));
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_KtCButtonActionPerformed

    private void FtKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FtKButtonActionPerformed
        // TODO add your handling code here:
        Double input = Double.parseDouble(inputField.getText());
        String inputS="FtK";
       try {
            osToServer.writeDouble(input);
            osToServer.writeUTF(inputS);
            osToServer.flush();
            
            double answer = isFromServer.readDouble();
            outputField.setText(twoDigits.format(answer));
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_FtKButtonActionPerformed

    private void KtFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KtFButtonActionPerformed
        // TODO add your handling code here:
        Double input = Double.parseDouble(inputField.getText());
        String inputS="KtF";
        try {
            osToServer.writeDouble(input);
            osToServer.writeUTF(inputS);
            osToServer.flush();
            
            double answer = isFromServer.readDouble();
            outputField.setText(twoDigits.format(answer));
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_KtFButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JNEx2Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JNEx2Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JNEx2Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JNEx2Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JNEx2Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CtFButton;
    private javax.swing.JButton CtKButton;
    private javax.swing.JButton FtCButton;
    private javax.swing.JButton FtKButton;
    private javax.swing.JButton KtCButton;
    private javax.swing.JButton KtFButton;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField outputField;
    // End of variables declaration//GEN-END:variables
}
